spring.application.name=jp-capacitacao

spring.datasource.url=${URL_DB:jdbc:oracle:thin:@localhost:1521:xe}
spring.datasource.username=${USERNAME_DB:admin}
spring.datasource.password=${PASSWORD_DB:admin}
spring.datasource.driver-class-name=${DRIVER:oracle.jdbc.OracleDriver}

spring.jpa.database-platform=${DIALECT:org.hibernate.dialect.OracleDialect}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${FORMAT_SQL:true}
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=${CONTEXTUAL_CREATION:true}
spring.jpa.properties.hibernate.id.uuid_generator=${UUID_GENERATOR:org.hibernate.id.uuid.UuidGenerator}

server.port=${PORT:8080}